-- 工作台空闲率
SET @interval_time = 60;
SET @line_num = 24;
SET @begin_time = '2021-07-21 07:00:00';
SELECT 
    seq.station_code AS station_code,
    cast((@interval_time * 60 - 
	    sum(CASE WHEN seq.entry_time >= @begin_time  
    	AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time MINUTE)
	    AND seq.exit_time < DATE_ADD(@begin_time , INTERVAL @interval_time MINUTE) 
    	THEN timestampdiff(SECOND,seq.entry_time,seq.exit_time)
        WHEN seq.entry_time >= @begin_time  AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time MINUTE) 
		THEN timestampdiff(second,seq.entry_time,DATE_ADD(@begin_time ,INTERVAL @interval_time MINUTE))
		ELSE 0 END))/(@interval_time*60)as decimal(10,2)) as '1',
		
    cast((@interval_time*60-
	    sum(CASE WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time MINUTE) 
    	AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*2 MINUTE)
      	AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*2 MINUTE)
    	THEN timestampdiff(second,seq.entry_time,seq.exit_time)
        WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*2 MINUTE)
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*2 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,DATE_ADD(@begin_time ,INTERVAL @interval_time*2 MINUTE))
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*2 MINUTE) 
		AND seq.exit_time>= DATE_ADD(@begin_time ,INTERVAL @interval_time MINUTE)
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*2 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time MINUTE),seq.exit_time)
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*2 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*2 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time MINUTE),DATE_ADD(@begin_time ,INTERVAL @interval_time*2 MINUTE))
        ELSE 0 END))/(@interval_time*60)as decimal(10,2)) as '2',
		
    cast((@interval_time*60-
	    sum(CASE WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*2 MINUTE) 
	    AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*3 MINUTE) 
     	AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*3 MINUTE) 
    	THEN timestampdiff(second,seq.entry_time,seq.exit_time)
        WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*2 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*3 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*3 MINUTE)
		THEN timestampdiff(second,seq.entry_time,DATE_ADD(@begin_time ,INTERVAL @interval_time*3 MINUTE))
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*2 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*3 MINUTE) 
		AND seq.exit_time>= DATE_ADD(@begin_time ,INTERVAL @interval_time*2 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*3 MINUTE)
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*2 MINUTE),seq.exit_time)
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*2 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*3 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*3 MINUTE)
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*2 MINUTE),DATE_ADD(@begin_time ,INTERVAL @interval_time*3 MINUTE))
        ELSE 0 END))/(@interval_time*60)as decimal(10,2)) as '3',
		
	cast((@interval_time*60-
	    sum(CASE WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*3 MINUTE) 
	    AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*4 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*4 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,seq.exit_time)
        WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*3 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*4 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*4 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,DATE_ADD(@begin_time ,INTERVAL @interval_time*4 MINUTE))
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*3 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*4 MINUTE)
		AND seq.exit_time>= DATE_ADD(@begin_time ,INTERVAL @interval_time*3 MINUTE)
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*4 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*3 MINUTE),seq.exit_time)
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*3 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*4 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*4 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*3 MINUTE),DATE_ADD(@begin_time ,INTERVAL @interval_time*4 MINUTE))
        ELSE 0 END))/(@interval_time*60)as decimal(10,2)) as '4',
		
	cast((@interval_time*60-
	    sum(CASE WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*4 MINUTE)
	    AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*5 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*5 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,seq.exit_time)
        WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*4 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*5 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*5 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,DATE_ADD(@begin_time ,INTERVAL @interval_time*5 MINUTE))
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*4 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*5 MINUTE)
		AND seq.exit_time>= DATE_ADD(@begin_time ,INTERVAL @interval_time*4 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*5 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*4 MINUTE),seq.exit_time)
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*4 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*5 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*5 MINUTE)
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*4 MINUTE),DATE_ADD(@begin_time ,INTERVAL @interval_time*5 MINUTE))
        ELSE 0 END))/(@interval_time*60)as decimal(10,2)) as '5',
		
	cast((@interval_time*60-
	    sum(CASE WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*5 MINUTE) 
	    AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*6 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*6 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,seq.exit_time)
        WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*5 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*6 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*6 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,DATE_ADD(@begin_time ,INTERVAL @interval_time*6 MINUTE))
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*5 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*6 MINUTE)
		AND seq.exit_time>= DATE_ADD(@begin_time ,INTERVAL @interval_time*5 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*6 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*5 MINUTE),seq.exit_time)
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*5 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*6 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*6 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*5 MINUTE),DATE_ADD(@begin_time ,INTERVAL @interval_time*6 MINUTE))
        ELSE 0 END))/(@interval_time*60)as decimal(10,2)) as '6',
		
    cast((@interval_time*60-
	    sum(CASE WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*6 MINUTE) 
	    AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*7 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*7 MINUTE)
		THEN timestampdiff(second,seq.entry_time,seq.exit_time)
        WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*6 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*7 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*7 MINUTE)
		THEN timestampdiff(second,seq.entry_time,DATE_ADD(@begin_time ,INTERVAL @interval_time*7 MINUTE))
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*6 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*7 MINUTE)
		AND seq.exit_time>= DATE_ADD(@begin_time ,INTERVAL @interval_time*6 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*7 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*6 MINUTE),seq.exit_time)
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*6 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*7 MINUTE)
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*7 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*6 MINUTE),DATE_ADD(@begin_time ,INTERVAL @interval_time*7 MINUTE))
        ELSE 0 END))/(@interval_time*60)as decimal(10,2)) as '7',
		
	cast((@interval_time*60-
	    sum(CASE WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*7 MINUTE)
     	AND seq.entry_time < DATE_ADD(@begin_time , INTERVAL @interval_time*8 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*8 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,seq.exit_time)
        WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*7 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*8 MINUTE)
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*8 MINUTE)
		THEN timestampdiff(second,seq.entry_time,DATE_ADD(@begin_time ,INTERVAL @interval_time*8 MINUTE))
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*7 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*8 MINUTE)
		AND seq.exit_time>= DATE_ADD(@begin_time ,INTERVAL @interval_time*7 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*8 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*7 MINUTE),seq.exit_time)
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*7 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*8 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*8 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*7 MINUTE),DATE_ADD(@begin_time ,INTERVAL @interval_time*8 MINUTE))
        ELSE 0 END))/(@interval_time*60)as decimal(10,2)) as '8',
		
	cast((@interval_time*60-
	    sum(CASE WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*8 MINUTE)
     	AND seq.entry_time < DATE_ADD(@begin_time , INTERVAL @interval_time*9 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*9 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,seq.exit_time)
        WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*8 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*9 MINUTE)
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*9 MINUTE)
		THEN timestampdiff(second,seq.entry_time,DATE_ADD(@begin_time ,INTERVAL @interval_time*9 MINUTE))
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*8 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*9 MINUTE)
		AND seq.exit_time>= DATE_ADD(@begin_time ,INTERVAL @interval_time*8 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*9 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*8 MINUTE),seq.exit_time)
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*8 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*9 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*9 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*8 MINUTE),DATE_ADD(@begin_time ,INTERVAL @interval_time*9 MINUTE))
        ELSE 0 END))/(@interval_time*60)as decimal(10,2)) as '9',
		
    cast((@interval_time*60-
	    sum(CASE WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*9 MINUTE)
     	AND seq.entry_time < DATE_ADD(@begin_time , INTERVAL @interval_time*10 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*10 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,seq.exit_time)
        WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*9 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*10 MINUTE)
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*10 MINUTE)
		THEN timestampdiff(second,seq.entry_time,DATE_ADD(@begin_time ,INTERVAL @interval_time*10 MINUTE))
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*9 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*10 MINUTE)
		AND seq.exit_time>= DATE_ADD(@begin_time ,INTERVAL @interval_time*9 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*10 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*9 MINUTE),seq.exit_time)
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*9 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*10 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*10 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*9 MINUTE),DATE_ADD(@begin_time ,INTERVAL @interval_time*10 MINUTE))
        ELSE 0 END))/(@interval_time*60)as decimal(10,2)) as '10',
		
	cast((@interval_time*60-
	    sum(CASE WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*10 MINUTE)
     	AND seq.entry_time < DATE_ADD(@begin_time , INTERVAL @interval_time*11 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*11 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,seq.exit_time)
        WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*10 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*11 MINUTE)
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*11 MINUTE)
		THEN timestampdiff(second,seq.entry_time,DATE_ADD(@begin_time ,INTERVAL @interval_time*11 MINUTE))
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*10 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*11 MINUTE)
		AND seq.exit_time>= DATE_ADD(@begin_time ,INTERVAL @interval_time*10 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*11 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*10 MINUTE),seq.exit_time)
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*10 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*11 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*11 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*10 MINUTE),DATE_ADD(@begin_time ,INTERVAL @interval_time*11 MINUTE))
        ELSE 0 END))/(@interval_time*60)as decimal(10,2)) as '11',
		
    cast((@interval_time*60-
		sum(CASE WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*11 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*12 MINUTE)
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*12 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,seq.exit_time)
        WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*11 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*12 MINUTE)
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*12 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,DATE_ADD(@begin_time ,INTERVAL @interval_time*12 MINUTE))
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*11 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*12 MINUTE) 
		AND seq.exit_time>= DATE_ADD(@begin_time ,INTERVAL @interval_time*11 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*12 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*11 MINUTE),seq.exit_time)
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*11 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*12 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*12 MINUTE)
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*11 MINUTE),DATE_ADD(@begin_time ,INTERVAL @interval_time*12 MINUTE))
        ELSE 0 END))/(@interval_time*60)as decimal(10,2)) as '12',
		
	cast((@interval_time*60-
		sum(CASE WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*12 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*13 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*13 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,seq.exit_time)
        WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*12 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*13 MINUTE)
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*13 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,DATE_ADD(@begin_time ,INTERVAL @interval_time*13 MINUTE))
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*12 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*13 MINUTE) 
		AND seq.exit_time>= DATE_ADD(@begin_time ,INTERVAL @interval_time*12 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*13 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*12 MINUTE),seq.exit_time)
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*12 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*13 MINUTE)
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*13 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*12 MINUTE),DATE_ADD(@begin_time ,INTERVAL @interval_time*13 MINUTE))
        ELSE 0 END))/(@interval_time*60)as decimal(10,2)) as '13',
		
	cast((@interval_time*60
		-sum(CASE WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*13 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*14 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*14 MINUTE)
		THEN timestampdiff(second,seq.entry_time,seq.exit_time)
        WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*13 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*14 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*14 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,DATE_ADD(@begin_time ,INTERVAL @interval_time*14 MINUTE))
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*13 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*14 MINUTE) 
		AND seq.exit_time>= DATE_ADD(@begin_time ,INTERVAL @interval_time*13 MINUTE)
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*14 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*13 MINUTE),seq.exit_time)
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*13 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*14 MINUTE)
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*14 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*13 MINUTE),DATE_ADD(@begin_time ,INTERVAL @interval_time*14 MINUTE))
        ELSE 0 END))/(@interval_time*60)as decimal(10,2)) as '14',
		
	cast((@interval_time*60
		-sum(CASE WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*14 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*15 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*15 MINUTE)
		THEN timestampdiff(second,seq.entry_time,seq.exit_time)
        WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*14 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*15 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*15 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,DATE_ADD(@begin_time ,INTERVAL @interval_time*15 MINUTE))
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*14 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*15 MINUTE) 
		AND seq.exit_time>= DATE_ADD(@begin_time ,INTERVAL @interval_time*14 MINUTE)
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*15 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*14 MINUTE),seq.exit_time)
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*14 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*15 MINUTE)
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*15 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*14 MINUTE),DATE_ADD(@begin_time ,INTERVAL @interval_time*15 MINUTE))
        ELSE 0 END))/(@interval_time*60)as decimal(10,2)) as '15',
		
	cast((@interval_time*60
		-sum(CASE WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*15 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*16 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*16 MINUTE)
		THEN timestampdiff(second,seq.entry_time,seq.exit_time)
        WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*15 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*16 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*16 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,DATE_ADD(@begin_time ,INTERVAL @interval_time*16 MINUTE))
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*15 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*16 MINUTE) 
		AND seq.exit_time>= DATE_ADD(@begin_time ,INTERVAL @interval_time*15 MINUTE)
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*16 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*15 MINUTE),seq.exit_time)
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*15 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*16 MINUTE)
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*16 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*15 MINUTE),DATE_ADD(@begin_time ,INTERVAL @interval_time*16 MINUTE))
        ELSE 0 END))/(@interval_time*60)as decimal(10,2)) as '16',
		
	cast((@interval_time*60
		-sum(CASE WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time* 16 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*17 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*17 MINUTE)
		THEN timestampdiff(second,seq.entry_time,seq.exit_time)
        WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*16 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*17 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*17 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,DATE_ADD(@begin_time ,INTERVAL @interval_time*17 MINUTE))
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*16 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*17 MINUTE) 
		AND seq.exit_time>= DATE_ADD(@begin_time ,INTERVAL @interval_time*16 MINUTE)
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*17 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*16 MINUTE),seq.exit_time)
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*16 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*17 MINUTE)
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*17 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*16 MINUTE),DATE_ADD(@begin_time ,INTERVAL @interval_time*17 MINUTE))
        ELSE 0 END))/(@interval_time*60)as decimal(10,2)) as '17',
		
	cast((@interval_time*60
		-sum(CASE WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*17 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*18 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*18 MINUTE)
		THEN timestampdiff(second,seq.entry_time,seq.exit_time)
        WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*17 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*18 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*18 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,DATE_ADD(@begin_time ,INTERVAL @interval_time*18 MINUTE))
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*17 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*18 MINUTE) 
		AND seq.exit_time>= DATE_ADD(@begin_time ,INTERVAL @interval_time*17 MINUTE)
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*18 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*17 MINUTE),seq.exit_time)
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*17 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*18 MINUTE)
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*18 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*17 MINUTE),DATE_ADD(@begin_time ,INTERVAL @interval_time*18 MINUTE))
        ELSE 0 END))/(@interval_time*60)as decimal(10,2)) as '18',
		
	cast((@interval_time*60
		-sum(CASE WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*18 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*19 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*19 MINUTE)
		THEN timestampdiff(second,seq.entry_time,seq.exit_time)
        WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*18 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*19 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*19 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,DATE_ADD(@begin_time ,INTERVAL @interval_time*19 MINUTE))
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*18 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*19 MINUTE) 
		AND seq.exit_time>= DATE_ADD(@begin_time ,INTERVAL @interval_time*18 MINUTE)
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*19 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*18 MINUTE),seq.exit_time)
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*18 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*19 MINUTE)
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*19 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*18 MINUTE),DATE_ADD(@begin_time ,INTERVAL @interval_time*19 MINUTE))
        ELSE 0 END))/(@interval_time*60)as decimal(10,2)) as '19',
		
	cast((@interval_time*60
		-sum(CASE WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*19 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*20 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*20 MINUTE)
		THEN timestampdiff(second,seq.entry_time,seq.exit_time)
        WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*19 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*20 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*20 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,DATE_ADD(@begin_time ,INTERVAL @interval_time*20 MINUTE))
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*19 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*20 MINUTE) 
		AND seq.exit_time>= DATE_ADD(@begin_time ,INTERVAL @interval_time*19 MINUTE)
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*20 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*19 MINUTE),seq.exit_time)
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*19 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*20 MINUTE)
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*20 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*19 MINUTE),DATE_ADD(@begin_time ,INTERVAL @interval_time*20 MINUTE))
        ELSE 0 END))/(@interval_time*60)as decimal(10,2)) as '20',
		
	cast((@interval_time*60
		-sum(CASE WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*20 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*21 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*21 MINUTE)
		THEN timestampdiff(second,seq.entry_time,seq.exit_time)
        WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*20 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*21 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*21 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,DATE_ADD(@begin_time ,INTERVAL @interval_time*21 MINUTE))
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*20 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*21 MINUTE) 
		AND seq.exit_time>= DATE_ADD(@begin_time ,INTERVAL @interval_time*20 MINUTE)
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*21 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*20 MINUTE),seq.exit_time)
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*20 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*21 MINUTE)
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*21 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*20 MINUTE),DATE_ADD(@begin_time ,INTERVAL @interval_time*21 MINUTE))
        ELSE 0 END))/(@interval_time*60)as decimal(10,2)) as '21',
		
	cast((@interval_time*60
		-sum(CASE WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*21 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*22 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*22 MINUTE)
		THEN timestampdiff(second,seq.entry_time,seq.exit_time)
        WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*21 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*22 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*22 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,DATE_ADD(@begin_time ,INTERVAL @interval_time*22 MINUTE))
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*21 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*22 MINUTE) 
		AND seq.exit_time>= DATE_ADD(@begin_time ,INTERVAL @interval_time*21 MINUTE)
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*22 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*21 MINUTE),seq.exit_time)
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*21 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*22 MINUTE)
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*22 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*21 MINUTE),DATE_ADD(@begin_time ,INTERVAL @interval_time*22 MINUTE))
        ELSE 0 END))/(@interval_time*60)as decimal(10,2)) as '22',
		
	cast((@interval_time*60
		-sum(CASE WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*22 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*23 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*23 MINUTE)
		THEN timestampdiff(second,seq.entry_time,seq.exit_time)
        WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*22 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*23 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*23 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,DATE_ADD(@begin_time ,INTERVAL @interval_time*23 MINUTE))
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*22 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*23 MINUTE) 
		AND seq.exit_time>= DATE_ADD(@begin_time ,INTERVAL @interval_time*22 MINUTE)
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*23 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*22 MINUTE),seq.exit_time)
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*22 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*23 MINUTE)
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*23 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*22 MINUTE),DATE_ADD(@begin_time ,INTERVAL @interval_time*23 MINUTE))
        ELSE 0 END))/(@interval_time*60)as decimal(10,2)) as '23',
		
	cast((@interval_time*60
		-sum(CASE WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*23 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*24 MINUTE) 
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*24 MINUTE)
		THEN timestampdiff(second,seq.entry_time,seq.exit_time)
        WHEN seq.entry_time >= DATE_ADD(@begin_time ,INTERVAL @interval_time*23 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*24 MINUTE) 
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*24 MINUTE) 
		THEN timestampdiff(second,seq.entry_time,DATE_ADD(@begin_time ,INTERVAL @interval_time*24 MINUTE))
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*23 MINUTE)
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*24 MINUTE) 
		AND seq.exit_time>= DATE_ADD(@begin_time ,INTERVAL @interval_time*23 MINUTE)
		AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*24 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*23 MINUTE),seq.exit_time)
        WHEN seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*23 MINUTE) 
		AND seq.entry_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*24 MINUTE)
		AND seq.exit_time > DATE_ADD(@begin_time ,INTERVAL @interval_time*24 MINUTE) 
		THEN timestampdiff(second,DATE_ADD(@begin_time ,INTERVAL @interval_time*23 MINUTE),DATE_ADD(@begin_time ,INTERVAL @interval_time*24 MINUTE))
        ELSE 0 END))/(@interval_time*60)as decimal(10,2)) as '24'
		
FROM evo_station.station_entry seq

WHERE seq.entry_time >= @begin_time  
  AND seq.exit_time < DATE_ADD(@begin_time ,INTERVAL @interval_time*@line_num MINUTE)
  AND idempotent_id LIKE '%G2PPicking%' 
  
GROUP BY seq.station_code